In [1]:
import torch

In [19]:
torch.manual_seed(0)
n1 = torch.rand(10, 5)[:, :]
n2 = n1[:, :, None, None].repeat(1, 1, 5, 5)

In [20]:
n1.size()

torch.Size([10, 5])

In [34]:
n2.size()

torch.Size([10, 5, 5, 5])

In [32]:
torch.rand(10, 3).permute(1, 0)

tensor([[0.0340, 0.0012, 0.4177, 0.2038, 0.8579, 0.1757, 0.1100, 0.8369, 0.0237,
         0.1143],
        [0.9442, 0.5936, 0.2711, 0.6833, 0.6870, 0.7497, 0.2121, 0.2820, 0.4910,
         0.4725],
        [0.8802, 0.4158, 0.6923, 0.7529, 0.0051, 0.6047, 0.9704, 0.3742, 0.1235,
         0.5751]])

In [35]:
n2.permute(2,1,0,3)

tensor([[[[0.4963, 0.4963, 0.4963, 0.4963, 0.4963],
          [0.6341, 0.6341, 0.6341, 0.6341, 0.6341],
          [0.3489, 0.3489, 0.3489, 0.3489, 0.3489],
          ...,
          [0.0317, 0.0317, 0.0317, 0.0317, 0.0317],
          [0.5263, 0.5263, 0.5263, 0.5263, 0.5263],
          [0.2422, 0.2422, 0.2422, 0.2422, 0.2422]],

         [[0.7682, 0.7682, 0.7682, 0.7682, 0.7682],
          [0.4901, 0.4901, 0.4901, 0.4901, 0.4901],
          [0.4017, 0.4017, 0.4017, 0.4017, 0.4017],
          ...,
          [0.2081, 0.2081, 0.2081, 0.2081, 0.2081],
          [0.2437, 0.2437, 0.2437, 0.2437, 0.2437],
          [0.8155, 0.8155, 0.8155, 0.8155, 0.8155]],

         [[0.0885, 0.0885, 0.0885, 0.0885, 0.0885],
          [0.8964, 0.8964, 0.8964, 0.8964, 0.8964],
          [0.0223, 0.0223, 0.0223, 0.0223, 0.0223],
          ...,
          [0.9298, 0.9298, 0.9298, 0.9298, 0.9298],
          [0.5846, 0.5846, 0.5846, 0.5846, 0.5846],
          [0.7932, 0.7932, 0.7932, 0.7932, 0.7932]],

         [[0.

In [24]:
n2.swapaxes(0, 2)

tensor([[[[0.4963, 0.4963, 0.4963, 0.4963, 0.4963],
          [0.6341, 0.6341, 0.6341, 0.6341, 0.6341],
          [0.3489, 0.3489, 0.3489, 0.3489, 0.3489],
          ...,
          [0.0317, 0.0317, 0.0317, 0.0317, 0.0317],
          [0.5263, 0.5263, 0.5263, 0.5263, 0.5263],
          [0.2422, 0.2422, 0.2422, 0.2422, 0.2422]],

         [[0.7682, 0.7682, 0.7682, 0.7682, 0.7682],
          [0.4901, 0.4901, 0.4901, 0.4901, 0.4901],
          [0.4017, 0.4017, 0.4017, 0.4017, 0.4017],
          ...,
          [0.2081, 0.2081, 0.2081, 0.2081, 0.2081],
          [0.2437, 0.2437, 0.2437, 0.2437, 0.2437],
          [0.8155, 0.8155, 0.8155, 0.8155, 0.8155]],

         [[0.0885, 0.0885, 0.0885, 0.0885, 0.0885],
          [0.8964, 0.8964, 0.8964, 0.8964, 0.8964],
          [0.0223, 0.0223, 0.0223, 0.0223, 0.0223],
          ...,
          [0.9298, 0.9298, 0.9298, 0.9298, 0.9298],
          [0.5846, 0.5846, 0.5846, 0.5846, 0.5846],
          [0.7932, 0.7932, 0.7932, 0.7932, 0.7932]],

         [[0.

In [1]:
from ddpm import UNET

In [2]:
model = UNET()

In [3]:
sum(param.numel() for param in model.parameters())

16656515